<?php
namespace App\Services;
use ZipArchive;
final class XlsxExporter {
 private array $sheets=[];
 public function addSheet(string $name,array $rows):self{$clean=preg_replace('/[\\\/?*\[\]:]/','-',$name);$clean=function_exists('mb_substr')?mb_substr($clean,0,31):substr($clean,0,31);$this->sheets[]=['name'=>$clean,'rows'=>$rows];return $this;}
 private function x(string $v):string{return htmlspecialchars($v,ENT_XML1|ENT_QUOTES,'UTF-8');}
 private function col(int $n):string{$s='';while($n>0){$n--; $s=chr(65+$n%26).$s;$n=intdiv($n,26);}return $s;}
 private function colsXml(array $rows):string{$max=[];foreach($rows as $row)foreach(array_values($row) as $i=>$v)$max[$i]=max($max[$i]??0,strlen((string)$v));$x='<cols>';foreach($max as $i=>$n){$w=max(10,min(60,$n+2));$c=$i+1;$x.='<col min="'.$c.'" max="'.$c.'" width="'.$w.'" customWidth="1"/>'; }return $x.'</cols>';}
 private function sheetXml(array $rows):string{$out='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><sheetFormatPr defaultRowHeight="18"/>'.$this->colsXml($rows).'<sheetData>';
  foreach($rows as $ri=>$row){$r=$ri+1;$out.='<row r="'.$r.'">';foreach(array_values($row) as $ci=>$value){$ref=$this->col($ci+1).$r;$style=$ri===0?1:0;if(is_int($value)||is_float($value)){$out.='<c r="'.$ref.'" s="'.$style.'" t="n"><v>'.$value.'</v></c>';}else{$text=(string)$value;if(preg_match('/^[=+\-@]/',$text))$text="'".$text;$out.='<c r="'.$ref.'" s="'.$style.'" t="inlineStr"><is><t xml:space="preserve">'.$this->x($text).'</t></is></c>';}}$out.='</row>';}
  return $out.'</sheetData><autoFilter ref="A1:'.$this->col(max(1,count($rows[0]??[]))).max(1,count($rows)).'"/><pageMargins left="0.3" right="0.3" top="0.5" bottom="0.5" header="0.2" footer="0.2"/></worksheet>';}
 public function save(string $path):void{if(!$this->sheets)throw new \RuntimeException('No worksheets supplied.');$z=new ZipArchive();if($z->open($path,ZipArchive::CREATE|ZipArchive::OVERWRITE)!==true)throw new \RuntimeException('Cannot create XLSX file.');
  $over=[];$rels=[];$book=[];foreach($this->sheets as $i=>$s){$n=$i+1;$over[]='<Override PartName="/xl/worksheets/sheet'.$n.'.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>';$rels[]='<Relationship Id="rId'.$n.'" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet'.$n.'.xml"/>';$book[]='<sheet name="'.$this->x($s['name']).'" sheetId="'.$n.'" r:id="rId'.$n.'"/>';$z->addFromString('xl/worksheets/sheet'.$n.'.xml',$this->sheetXml($s['rows']));}
  $z->addFromString('[Content_Types].xml','<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>'.implode('',$over).'</Types>');
  $z->addFromString('_rels/.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>');
  $z->addFromString('xl/workbook.xml','<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>'.implode('',$book).'</sheets></workbook>');
  $rels[]='<Relationship Id="rId'.(count($this->sheets)+1).'" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>';$z->addFromString('xl/_rels/workbook.xml.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'.implode('',$rels).'</Relationships>');
  $z->addFromString('xl/styles.xml','<?xml version="1.0" encoding="UTF-8"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Calibri"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="11"/><name val="Calibri"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF17365D"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders><cellXfs count="2"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1"/></cellXfs></styleSheet>');$z->close();}
}
