<?php include __DIR__.'/../../../includes/header.php'; ?>
<div class="hero"><div><h2>Project Management Overview</h2><p>Portfolio progress, exceptions and actions requiring management attention.</p></div><div><a class="btn light" href="select_project.php">Open Progress Tracker</a></div></div>
<div class="stats-grid">
<div class="stat-card"><span>Assigned Projects</span><strong><?=$stats['projects']?></strong><small>Visible to your account</small></div>
<div class="stat-card"><span>Weighted Progress</span><strong><?=$actual?>%</strong><small>Planned <?=$planned?>% · Variance <?=$variance>0?'+':''?><?=$variance?>%</small></div>
<div class="stat-card"><span>Overdue Activities</span><strong><?=$stats['overdue']?></strong><small>Incomplete beyond end date</small></div>
<div class="stat-card"><span>Open Procurement</span><strong><?=$stats['procurement_open']?></strong><small>Not yet received or delivered</small></div>
<div class="stat-card"><span>MAS Action</span><strong><?=$stats['mas_action']?></strong><small>Under review, resubmit or rejected</small></div>
<div class="stat-card"><span>Near Due</span><strong><?=$stats['near_due']?></strong><small>Activities due within 7 days</small></div>
<div class="stat-card"><span>Missing Activity Dates</span><strong><?=$stats['missing_dates']?></strong><small>Planned activity end date required</small></div>
</div>
<section class="panel"><div class="panel-head"><div><h2>Project Performance</h2><p class="muted">Weighted measurable-item actual versus planned progress.</p></div><a href="export_management_xlsx.php" class="btn">Export Management XLSX</a></div>
<div class="table-wrap"><table><thead><tr><th>Project</th><th>Planned</th><th>Actual</th><th>Variance</th><th>Performance</th></tr></thead><tbody><?php foreach($projects as $p):$v=round((float)$p['actual']-(float)$p['planned'],1);?><tr><td><strong><?=e($p['project_name'])?></strong></td><td><?=e((string)$p['planned'])?>%</td><td><?=e((string)$p['actual'])?>%</td><td style="color:<?=$v<0?'#B91C1C':'#166534'?>"><?=$v>0?'+':''?><?=$v?>%</td><td><div class="progress-mini"><span style="width:<?=max(0,min(100,(float)$p['actual']))?>%"></span></div></td></tr><?php endforeach?><?php if(!$projects):?><tr><td colspan="5" class="empty">No assigned projects.</td></tr><?php endif?></tbody></table></div></section>
<section class="panel"><div class="panel-head"><div><h2>Management Alerts</h2><p class="muted">Prioritized schedule, progress, procurement, submittal and work-plan exceptions.</p></div></div><div class="table-wrap"><table><thead><tr><th>Severity</th><th>Alert</th><th>Project</th><th>Description</th><th>Due/Threshold</th><th>Days/Variance</th><th>Source</th></tr></thead><tbody><?php foreach($alerts as $a):?><tr><td><span class="badge" style="background:<?=$a['severity']==='Critical'?'#FEE2E2':($a['severity']==='High'?'#FEF3C7':'#E0F2FE')?>;color:#172033"><?=e($a['severity'])?></span></td><td><?=e($a['alert_type'])?></td><td><?=e($a['project_name'])?></td><td><?=e($a['description'])?></td><td><?=e($a['due_date']??'')?></td><td><?=e((string)$a['days_value'])?></td><td><?=e($a['source_module'])?></td></tr><?php endforeach?><?php if(!$alerts):?><tr><td colspan="7" class="empty">No active management alerts.</td></tr><?php endif?></tbody></table></div></section>
<?php include __DIR__.'/../../../includes/footer.php';?>
