<?php
require_login();
use App\Services\ManagementDashboard;use App\Services\XlsxExporter;
$data=(new ManagementDashboard($pdo,project_scope_clause('p.id')))->data();
$summary=[['Metric','Value'],['Assigned Projects',$data['stats']['projects']],['Weighted Actual Progress',(float)$data['portfolio']['actual']],['Weighted Planned Progress',(float)$data['portfolio']['planned']],['Variance',round((float)$data['portfolio']['actual']-(float)$data['portfolio']['planned'],1)],['Overdue Activities',$data['stats']['overdue']],['Open Procurement',$data['stats']['procurement_open']],['MAS Requiring Action',$data['stats']['mas_action']],['Near Due Activities',$data['stats']['near_due']],['Missing Activity Dates',$data['stats']['missing_dates']]];
$projects=[['Project','Planned %','Actual %','Variance %']];foreach($data['projects'] as $p)$projects[]=[(string)$p['project_name'],(float)$p['planned'],(float)$p['actual'],round((float)$p['actual']-(float)$p['planned'],1)];
$alerts=[['Severity','Alert Type','Project','Description','Due/Threshold','Days / Variance','Source']];foreach($data['alerts'] as $a)$alerts[]=[$a['severity'],$a['alert_type'],$a['project_name'],$a['description'],$a['due_date'],(float)$a['days_value'],$a['source_module']];
$file=sys_get_temp_dir().'/MEP_Management_Report_'.date('Y-m-d').'_' .bin2hex(random_bytes(6)).'.xlsx';try{(new XlsxExporter())->addSheet('Executive Summary',$summary)->addSheet('Project Performance',$projects)->addSheet('Management Alerts',$alerts)->save($file);}catch(Throwable $e){error_log('Management XLSX export failed: '.$e->getMessage());flash('error','The management workbook could not be generated. Confirm that PHP ZipArchive is enabled.');redirect('dashboard.php');}audit_event($pdo,'export','exports',null,null,'Management XLSX exported');
header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="'.basename($file).'"');header('Content-Length: '.filesize($file));readfile($file);@unlink($file);exit;
