<?php
require_login();
use App\Services\ProgressCalculator;use App\Services\XlsxExporter;
$projectId=(int)($_GET['project_id']??0);if(!$projectId){flash('error','Select a project first.');redirect('projects.php');}require_project_permission($pdo,$projectId,'report.export');
$s=$pdo->prepare('SELECT * FROM projects WHERE id=?');$s->execute([$projectId]);$project=$s->fetch();if(!$project){flash('error','Project not found.');redirect('projects.php');}
$s=$pdo->prepare('SELECT * FROM project_progress WHERE project_id=? ORDER BY discipline,boq_no,id');$s->execute([$projectId]);$items=$s->fetchAll();$calc=new ProgressCalculator($pdo);$totals=$calc->project($projectId);$disc=$calc->disciplines($projectId);
$summary=[['MEP PROJECT PROGRESS REPORT',''],['Project',$project['project_name']],['Location',$project['location']],['Client',$project['client']],['Report Date',date('Y-m-d')],['Planned Progress %',(float)$totals['planned']],['Actual Progress %',(float)$totals['actual']],['Variance %',(float)$totals['variance']]];
$discipline=[['Discipline','Measurable Items','Planned %','Actual %','Variance %']];foreach($disc as $d)$discipline[]=[$d['discipline'],(int)$d['measurable_items'],(float)$d['planned'],(float)$d['actual'],round((float)$d['actual']-(float)$d['planned'],1)];
$detail=[['Discipline','BOQ No.','Item Type','Task','Task Description','Material Quantity','Unit','Weight','Planned %','Actual %','Status','Planned Start','Planned End','Actual Start','Actual End','Start Source','Source Reference','Installation Start','Remarks']];foreach($items as $r)$detail[]=[$r['discipline'],$r['boq_no'],$r['item_type'],$r['task'],$r['material_description'],(float)($r['material_quantity']??0),$r['unit'],(float)$r['activity_weight'],round((float)$r['planned_percentage'],2),round((float)$r['percentage_complete'],2),$r['status'],$r['planned_start_date'],$r['planned_end_date'],$r['actual_start_date'],$r['actual_end_date'],$r['start_date_source'],$r['start_source_reference'],$r['installation_start_date'],$r['remarks']];
$safe=preg_replace('/[^A-Za-z0-9_-]/','_',trim($project['project_name']));$file=sys_get_temp_dir().'/MEP_Progress_'.$safe.'_'.date('Y-m-d').'_'.bin2hex(random_bytes(6)).'.xlsx';try{(new XlsxExporter())->addSheet('Project Summary',$summary)->addSheet('Discipline Summary',$discipline)->addSheet('BOQ Progress',$detail)->save($file);}catch(Throwable $e){error_log('XLSX export failed: '.$e->getMessage());flash('error','The Excel report could not be generated. Confirm that PHP ZipArchive is enabled.');redirect('project_progress.php?project_id='.$projectId);}audit_event($pdo,'export','exports',$projectId,$projectId,'Project XLSX exported');
header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="'.basename($file).'"');header('Content-Length: '.filesize($file));readfile($file);@unlink($file);exit;
