<?php
namespace App\Controllers;

use App\Core\Controller;use App\Core\Request;use App\Models\ProjectRoleAssignment;use App\Services\AssignmentConflict;use App\Services\AssignmentForbidden;use App\Services\AssignmentNotFound;use App\Services\ProjectAuthorization;use App\Services\ProjectRoleAssignmentService;use App\Services\StaleAssignment;use App\Services\ValidationException;

final class ProjectAssignmentApiController extends Controller
{
    private \PDO $db;private ProjectAuthorization $authorization;private ProjectRoleAssignmentService $service;
    public function __construct(){global$pdo;$this->db=$pdo;$this->authorization=new ProjectAuthorization($pdo);$this->service=new ProjectRoleAssignmentService($pdo,$this->authorization);}
    public function create(Request $r): void{$projectId=$this->positive($r->param('id'));$body=$r->body();try{$data=$this->service->create($projectId,$this->positive($body['user_id']??0),(string)($body['role_code']??''),$body['effective_from']??null,$body['effective_until']??null,(string)($body['reason']??''),(int)$_SESSION['user_id']);$this->json(['data'=>$this->publicAssignment($data),'request_id'=>\request_id()],201);}catch(\Throwable $e){$this->failure($e);}}
    public function update(Request $r): void{$id=$this->positive($r->param('id'));$body=$r->body();try{$data=$this->service->update($id,(string)($body['role_code']??''),$body['effective_from']??null,$body['effective_until']??null,(string)($body['reason']??''),$this->expectedVersion($body),(int)$_SESSION['user_id']);$this->json(['data'=>$this->publicAssignment($data),'request_id'=>\request_id()]);}catch(\Throwable $e){$this->failure($e);}}
    public function remove(Request $r): void{$id=$this->positive($r->param('id'));$body=$r->body();try{$this->service->revoke($id,(string)($body['reason']??''),$this->expectedVersion($body),(int)$_SESSION['user_id']);http_response_code(204);exit;}catch(\Throwable $e){$this->failure($e);}}
    public function userProjects(Request $r): void{$target=$this->positive($r->param('id'));$actor=(int)$_SESSION['user_id'];if($target!==$actor&&($_SESSION['role']??'')!=='admin')$this->json(['error'=>['code'=>'FORBIDDEN','message'=>'You cannot view another user’s project assignments.'],'request_id'=>\request_id()],403);$this->json(['data'=>$this->authorization->projectsForUser($target),'request_id'=>\request_id()]);}
    public function projectAssignments(Request $r): void{$projectId=$this->positive($r->param('id'));$this->authorization->require($projectId,'project.view');$this->json(['data'=>(new ProjectRoleAssignment($this->db))->forProject($projectId,false),'request_id'=>\request_id()]);}
    private function positive(mixed $value): int{$id=filter_var($value,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);if(!$id)$this->json(['error'=>['code'=>'BAD_REQUEST','message'=>'A positive identifier is required.'],'request_id'=>\request_id()],400);return(int)$id;}
    private function expectedVersion(array $body): int{$header=trim((string)($_SERVER['HTTP_IF_MATCH']??''));if($header==='')$this->json(['error'=>['code'=>'PRECONDITION_REQUIRED','message'=>'A quoted If-Match entity tag is required.'],'request_id'=>\request_id()],428);if(!preg_match('/^"(\d+)"$/',$header,$m))$this->json(['error'=>['code'=>'INVALID_ETAG','message'=>'If-Match must be a quoted numeric entity tag, for example "7".'],'request_id'=>\request_id()],422);return(int)$m[1];}
    private function publicAssignment(array $a): array{return array_intersect_key($a,array_flip(['id','project_id','user_id','user_name','email','role_code','role_name','effective_from','effective_until','active','assigned_at','version']));}
    private function failure(\Throwable $e): never{$status=500;$code='INTERNAL_ERROR';if($e instanceof ValidationException){$status=422;$code='VALIDATION_FAILED';}elseif($e instanceof AssignmentConflict){$status=409;$code='ASSIGNMENT_CONFLICT';}elseif($e instanceof StaleAssignment){$status=412;$code='STALE_VERSION';}elseif($e instanceof AssignmentNotFound){$status=404;$code='NOT_FOUND';}elseif($e instanceof AssignmentForbidden){$status=403;$code='FORBIDDEN';}if($status===500)error_log('Assignment API failure ['.\request_id().']: '.$e->getMessage());$message=$status===500?'The request could not be completed.':$e->getMessage();$this->json(['error'=>['code'=>$code,'message'=>$message],'request_id'=>\request_id()],$status);}
}
