<?php $pageTitle='Project Roles - '.e($project['project_name']);include __DIR__.'/../../../includes/header.php'; ?>
<section class="panel"><div class="panel-head"><div><h2>Project Members & Roles</h2><p class="muted">Secure, project-specific access for <?=e($project['project_name'])?>. Every change requires a reason and is retained in the audit history.</p></div><div class="assignment-tabs"><a class="btn ghost" href="projects.php">Back to Projects</a><?php if($rbacReady):?><a class="btn ghost" href="mvc.php?route=project-members&amp;project_id=<?=$project['id']?>&amp;history=<?=$history?'0':'1'?>"><?=$history?'Active Assignments':'Assignment History'?></a><?php endif?></div></div></section>
<?php if(!$rbacReady):?>
<section class="panel"><div class="rbac-migration-warning"><strong>Database upgrade required</strong><p>Current access continues through the legacy compatibility table. Import <code>database_upgrade.sql</code> in phpMyAdmin to enable role editing, soft revocation, permissions, integrity checks and assignment auditing.</p></div></section>
<section class="panel"><h2>Existing project assignments</h2><div class="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Project Role</th><th>Edit</th></tr></thead><tbody><?php foreach($members as $m):?><tr><td data-label="Name"><?=e($m['name'])?></td><td data-label="Email"><?=e($m['email'])?></td><td data-label="Project Role"><?=e($m['project_role'])?></td><td data-label="Edit"><?=$m['can_edit']?'Yes':'No'?></td></tr><?php endforeach?><?php if(!$members):?><tr><td colspan="4" class="empty">No project members assigned.</td></tr><?php endif?></tbody></table></div></section>
<?php else:?>
<?php if(!$history):?>
<section class="panel"><h2>Assign a Project Role</h2><form method="post" action="mvc.php?route=project-members-save" class="form-grid assignment-form"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="project_id" value="<?=$project['id']?>">
<label>User<select name="user_id" required><option value="">-- Select active user --</option><?php foreach($available as $u):?><option value="<?=$u['id']?>"><?=e($u['name'].' — '.$u['email'])?></option><?php endforeach?></select></label>
<label>Project Role<select name="role_code" class="role-selector" required><option value="">-- Select role --</option><?php foreach($roles as $r):?><option value="<?=e($r['code'])?>" <?=($r['code']==='project_manager'&&!has_role('admin'))?'disabled':''?>><?=e($r['name'])?></option><?php endforeach?></select></label>
<label>Effective From<input type="datetime-local" name="effective_from"></label><label>Effective Until<input type="datetime-local" name="effective_until"></label>
<label class="span-2">Reason <textarea name="reason" minlength="10" maxlength="500" required placeholder="Explain why this project access is required (10–500 characters)"></textarea></label>
<div class="permission-preview span-2" aria-live="polite"><strong>Permission preview</strong><span>Select a role to see its access.</span></div><div class="form-actions"><button class="btn" type="submit" <?=$available?'':'disabled'?>>Assign Role</button></div></form><?php if(!$available):?><p class="muted">Every active user already has an active assignment on this project.</p><?php endif?></section>
<?php endif?>
<section class="panel"><h2><?=$history?'Assignment History':'Active Assignments'?></h2><div class="table-wrap"><table class="assignments-table"><thead><tr><th>User</th><th>Role</th><th>Effective Window</th><th>Assigned By</th><th>Status</th><?php if(!$history):?><th>Change Role</th><th>Revoke</th><?php else:?><th>Revocation</th><?php endif?></tr></thead><tbody>
<?php foreach($members as $m):?><tr><td data-label="User"><strong><?=e($m['name'])?></strong><small><?=e($m['email'])?></small></td><td data-label="Role"><span class="role-badge role-<?=e(str_replace('-','_',$m['role_code']))?>"><?=e($m['role_name'])?></span></td><td data-label="Effective Window"><?=e($m['effective_from'])?><br><small>until <?=e($m['effective_until']?:'No expiry')?></small></td><td data-label="Assigned By"><?=e($m['assigned_by_name']?:'System')?><br><small><?=e($m['assigned_at'])?></small></td><td data-label="Status"><span class="badge <?=$m['active']?'badge-active':'badge-inactive'?>"><?=$m['active']?'Active':'Revoked'?></span></td>
<?php if(!$history):?><td data-label="Change Role"><details><summary>Edit</summary><form method="post" action="mvc.php?route=project-members-save" class="assignment-inline-form"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="project_id" value="<?=$project['id']?>"><input type="hidden" name="assignment_id" value="<?=$m['id']?>"><input type="hidden" name="version" value="<?=$m['version']?>"><select name="role_code" class="role-selector" required><?php foreach($roles as $r):?><option value="<?=e($r['code'])?>" <?=$m['role_code']===$r['code']?'selected':''?> <?=($r['code']==='project_manager'&&!has_role('admin'))?'disabled':''?>><?=e($r['name'])?></option><?php endforeach?></select><input type="datetime-local" name="effective_from" value="<?=e(str_replace(' ','T',substr((string)$m['effective_from'],0,16)))?>"><input type="datetime-local" name="effective_until" value="<?=e($m['effective_until']?str_replace(' ','T',substr((string)$m['effective_until'],0,16)):'')?>"><textarea name="reason" minlength="10" maxlength="500" required placeholder="Reason for role change"></textarea><button class="mini-btn" type="submit">Save Change</button></form></details></td><td data-label="Revoke"><form method="post" action="mvc.php?route=project-members-remove" class="assignment-revoke-form" onsubmit="return confirm('Revoke this project assignment? Access will end immediately.')"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="project_id" value="<?=$project['id']?>"><input type="hidden" name="assignment_id" value="<?=$m['id']?>"><input type="hidden" name="version" value="<?=$m['version']?>"><input name="reason" minlength="10" maxlength="500" required placeholder="Revocation reason"><button class="link-danger" type="submit">Revoke</button></form></td>
<?php else:?><td data-label="Revocation"><?=e($m['revoked_reason']?:'-')?><?php if($m['revoked_at']):?><br><small><?=e(($m['revoked_by_name']?:'System').' · '.$m['revoked_at'])?></small><?php endif?></td><?php endif?></tr><?php endforeach?>
<?php if(!$members):?><tr><td colspan="7" class="empty">No <?=$history?'historical':'active'?> assignments found.</td></tr><?php endif?></tbody></table></div></section>
<script>
(()=>{const permissions=<?=json_encode($rolePermissions,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_UNESCAPED_SLASHES)?>;document.querySelectorAll('.role-selector').forEach(select=>{const preview=select.closest('form')?.querySelector('.permission-preview span');const render=()=>{if(!preview)return;const list=permissions[select.value]||[];preview.textContent=list.length?list.join(' · '):'Select a role to see its access.'};select.addEventListener('change',render);render();});})();
</script>
<?php endif?>
<?php include __DIR__.'/../../../includes/footer.php'; ?>
